apiVersion: v1
kind: Pod
metadata:
  labels:
    Application: hmscommon
spec:
  hostAliases:
  - ip: "172.29.27.150"
    hostnames:
    - "maven.netgear.com"
  containers:
  - name: maven
    image: maven:3.6.0-alpine
    command: ["cat"]
    tty: true
    volumeMounts:
    - name: m2
      mountPath: /root/.m2
    - name: dockersock
      mountPath: /var/run/docker.sock
  - name: docker
    image: docker:1.11
    command: ["cat"]
    tty: true
    volumeMounts:
    - name: dockersock
      mountPath: /var/run/docker.sock
  volumes:
  - name: dockersock
    hostPath:
      path: /var/run/docker.sock
  - name: m2
    hostPath: 
      path: /root/.m2